---
- name: uninstall the iis web service
  hosts: windows
  tasks:
   - name: stop iis service
     win_service:
       name: W3Svc
       state: stopped

   - name: install iis
     win_feature:
       name: Web-Server
       state: absent
       register: iis_uninstall
      
   - name: Restart server
     win_reboot:
     when: iis_uninstall.reboot_required  
