---
- name: Install Application 
  win_chocolatey:
    name: "{{ jdk_package }}"
    state: present
    version: "{{ java_major_version }}.{{ java_minor_version }}"
    ignore_checksums: true
    
- name: reboot
  ansible.windows.win_reboot:
